database-host: 127.0.0.1
database-port: 3306
database-schema: ipet
database-username: root
database-password: 123456
ldap.domain: "@domain.sensetime.com"

#上传项目文件的路径及下载的地址和端口
LoadFileConfig:
  projectLocation: D:/ipet/load/project/
  projectPlanLocation: D:/ipet/load/projectPlan/
  topologicalGraphLocation:  D:/ipet/load/topologicalGraph/
  physicalMapLocation: D:/ipet/load/physicalMap/
  downloadIp: 127.0.0.1
  downloadPort: 8082
#web访问和服务器地址映射关系
web-to-disk: D:/ipet/
#redis 开发ip
redis-host: 127.0.0.1
#server port
server-port: 8082
